  <%@ include file="top.phtml" %>
    <title><%syspref var="site.name" %> :: <%$title %></title>
    <%$heads%>
  <%@ include file="header.phtml" %>
  <%@ include file="pagebegin.phtml" %>
  <div class="clearhack"></div>
  <%@ include file="sidebar.phtml" %>
  <% if data["object_is_weblog"] %>
    <div id="blogroll">
<%$content%>
    </div>
  <% else %>
    <div class="entry" id="<%$obj%>">
      <div class="meta">
	<h3 class="title"><%$title %></h3>
	<span>Published <%friendly_date var="$object_version.created"%> by <%$editor_username%></span>
	<% if data["numcategories"] %><ul class="tags">Tags:
	    <% foreach var="$object.categories" val="categories" %>
	      <li class="tag"><a href="/exec/category/<%$categories.category%>"><%$categories.category%></a></li>
	    <% end %>
	  </ul>
	<% endif %><ul class="comments">
	  <li>
	    <% if data["numcomments"] %>
	      <a href="#" id="trigger_comments-<%$obj%>"><%$numcomments %> comments</a>
	    <% else %>
	      0 comments
	    <% endif %>
	    <a id="PostComment" href="/exec/comments/<%$obj%>">post a comment</a>
	  </li>
	  <li><a href="#" onclick="displayReferences('<%$obj%>')">references</a></li>
	  <% if data["numattachments"] %>
	    <li><a href="#" onclick="displayAttachments('<%$obj%>')"><%$numattachments%> attachments</a></li>
	  <% endif %>
	</ul>
      </div>
      <div class="content">
 <%$content%>
      </div>
      <div dojoType="fins.widget.Comments" refreshUrl="/exec/getcomments/<%$obj%>" id="<%$obj%>_comments" connectorId="trigger_comments-<%$obj%>"></div>
    </div>
  <% endif %>
  <%@ include file="footer.phtml" %>
  <%@ include file="bottom.phtml" %>
