<div class="entry" id="<%$entry.path%>"><div class="meta"><h3 class="title"><%$subject %></h3><span>Published <%$entry.nice_created%> by <%$entry.author.username%></span>
<% if sizeof(data["entry"]["categories"]) %>
<ul class="tags">Tags:<% foreach var="$entry.categories" val="category" %><li class="tag"><a 
href="/exec/category/<%$category.category%>"><%$category.category%></a></li><% end %></ul><% endif %><ul class="comments"><% if sizeof(data["entry"]["comments"]) %><li><a href="#" id="trigger_comments-<%$entry.id%>"><% sizeof var="$entry.comments" %> 
comments</a></li><% else %><li>0 comments</li><% endif %><li><a href="#" onclick="postComment('<%$entry.path%>')">post a comment</a></li><li><a href="#" onclick="displayReferences('<%$entry.path%>')">references</a></li><% if data["numattachments"] %><li><a href="#" onclick="displayAttachments('<%$obj%>')"><%$numattachments%> attachments</a></li><% endif %><% if data["teaser"] %><li><a href="/space/<%$entry.path%>">read more</a></li><% endif %><% if data["entry"]["md"]["views"] %><li><%$entry.md.views%> views</li><% endif %></ul>
</div>
<div class="content">
<% if data["teaser"] %><%render content="$teaser" object="$entry"%>
<% else %>
<%render content="$content" object="$entry"%><% endif %>
</div>
<div dojoType="fins.widget.Comments" refreshUrl="<%syspref var="site.url"%>/exec/getcomments/<%$entry.path%>" id="<%$entry.id%>_comments" connectorId="trigger_comments-<%$entry.id%>"></div>
</div>
