
<% if data["numcategories"] %>
 <%LOCALE id="105" string="Posted in "%><% implode var="$category_links" final=" and " %>.
<p/>
<% endif %>

<%if data["object_is_weblog"] %>
<% elseif sizeof(data["object"]["attachments"])%>
<h3><%LOCALE id="81" string="Attachments"%></h3>
<%@ include file="space/_displayattachments.phtml"%>
<p/>
<%endif %>


<% if data["object_is_weblog"] %>
<% else %>
<p class="comments clear">
         <b><% if data["numcomments"] %>
                                         <a href="#" id="trigger_comments-<%$obj%>"><%$numcomments %> comments</a>
            <% else %>
                 <%LOCALE id="106" string="No comments"%> 
            <% endif %>
 |  <%action_link _id="PostComment" controller="/exec" action="comments" args="$obj"%><%LOCALE id="11" string="Post a Comment"%></a> | 
<%action_link controller="/rss" args="$obj" type="comments"%><%LOCALE id="12" string="RSS Feed"%></a>
  <% if data["metadata"]["trackbacks"] %> | <%action_link controller="/exec" action="display_trackbacks" args="$obj" _id="TrackBacks"%><%sizeof var="$metadata.trackbacks"%> 
<%LOCALE id="100" string="TrackBacks"%></a> <% endif %>
  <% if data["metadata"]["pingbacks"] %> | <%action_link controller="/exec" action="display_pingbacks" args="$obj" _id="PingBacks"%><%sizeof var="$metadata.pingbacks"%> 
<%LOCALE id="101" string="PingBacks"%></a> <% endif %> 
| <%action_link controller="/exec" action="backlinks" args="$obj" _id="BackLinks"%><%LOCALE id="107" string="BackLinks"%></a>
         <p/>
                        <div dojoType="fins.widget.Comments" refreshUrl="<%action_url controller="/exec" action="getcomments" args="$obj"%>" id="<%$obj%>_comments" connectorId="trigger_comments-<%$obj%>"></div>
<% endif %>
</p>

</div>
</div>
</div>