
</div>

<div id="sidebar">
 <% snip snip="themes/default/portlet-1" %>

 <ul>
   <li><h2>Meta</h2>
   <ul>
   <%@include file="tagline.phtml"%>   
   </ul>
 </ul>
</div>


 <div id="footer"> 
<a href="<%syspref var="site.url"%>">home</a>&nbsp;&nbsp;:&nbsp;&nbsp; 
<a href="/space/contact%20info">contact info</a>
</br>
<center>
copyright &copy; 1995-2006 Bill Welliver
</p></center>
</div>


</div>
