<li> <a href="/space/start">Start</a> </li>
<li> <a href="/space/object-index">Index</a> </li>

<% if data["user_object"] %>
<li> <%action_link controller="/exec" action="logout"%>Logout</a> </li>
<li> <%action_link controller="/account"%>My Account</a> </li>
<% if data["object_is_weblog"] %>
<li> <a href="<%action_url controller="/exec" action="post" args="$metadata.weblog_source_path"%>" id="PostBlog">Post Blog</a> </li>
<% endif %>
<% if data["is_admin"]==1 %>
<li> <%action_link controller="/admin"%>Admin</a> </li>
   <% endif %>
   <% else %>
<li> <a href="<%action_url controller="/exec" action="login"%>" id="Login">Login</a> </li>
<% endif %>

<% if data["user_object"]  %>
<li> <a href="<%action_url controller="/exec" action="actions" args="$obj"%>" id="Actions">Actions</a> </li>
<% endif %>

