<li> <a href="/space/start">Start</a> </li>
<li> <a href="/space/object-index">Index</a> </li>
<% if data["user_object"] %>
<li> <a href="/exec/logout">Logout</a> </li>
<% if data["object_is_weblog"] %>
<li> <a href="/exec/port/<%$obj%>" id="PostBlog">Post Blog</a> </li>
<% endif %>
<% if data["is_admin"]==1 %>
<li> <a href="/admin/" id="Admin">Admin</a> </li>
   <% endif %>
   <% else %>
<li> <a href="/exec/login" id="Login">Login</a> </li>
<% endif %>

<% if data["user_object"]  %>
<li> <a href="/exec/actions/<%$obj%>" id="Actions">Actions</a> </li>
<% endif %>
