	<%@ include file="top.phtml" %>
        <%@ include file="header.phtml" %>
        <title><%syspref var="site.name" %> :: <%$title %></title>
        <%$heads %>

	<%@ include file="pagebegin.phtml" %>
<!-- we need to provide a header for wiki content. -->

        <% breadcrumbs var="$object.path" %>
        <%@ include file="space/trackback.phtml" %>

      <% if data["object_is_weblog"] %>
      <% else %>

                        <h2 class="posttitle"><a href="/space/<%$object.path%>" rel="bookmark" title="Permanent Link to <%$object.title%>">
                                 <%$object.title%></a></h2>

<p class="postmeta"><%$object.nice_created%> @ <%format_date var="$object.created" format="mod"%> <% if sizeof(data->object["categories"]) %> &#183; Filed under <% implode var="$object.category_links" final=" and "%><%endif%>
<%if data["user_object"] %>
&#183;  <a href="/exec/actions/<%$obj%>" id="Actions">actions</a>
<% endif %>
</p>

     <% endif %>
<div class="flash-message"><% flash %></div>
 <%$content%>
<p>

<% if data["object_is_weblog"] %>
<% else %>



                        <p class="postfeedback">
<a class="permalink" href="/space/<%$object.path%>" rel="bookmark" title="Permanent Link to <%$object.title%>">Permalink</a>
         <% if data["numcomments"] %>
                 <a class="commentslink" href="#" id="trigger_comments-<%$obj%>"><%$numcomments %> comments</a>
            <% else %>
                 No comments
            <% endif %>
/  <a class="commentslink" id="PostComment" href="/exec/comments/<%$obj%>"><%LOCALE id="11" string="Post a Comment"%></a>
</p>
   <div dojoType="fins.widget.Comments" refreshUrl="/exec/getcomments/<%$obj%>" id="<%$obj%>_comments" connectorId="trigger_comments-<%$obj%>"></div>
<% endif %>

<%@include file="pageend.phtml" %>
<%@include file="footer.phtml" %>
<%@include file="bottom.phtml" %>
