<div class="post" id="post-<%$entry.id%>">
                        <h2 class="posttitle"><a href="/space/<%$entry.path%>" rel="bookmark" title="Permanent Link to <%$subject%>">
                                 <%$subject%></a></h2>
<p class="postmeta"><%$entry.nice_created%> @ <%format_date var="$entry.created" format="mod"%> <% if sizeof(data->entry["categories"]) %> &#183; Filed under <% implode var="$entry.category_links" final=" and " 
%><%endif%></p>

                        <div class="postentry">
  <%render content="$content" object="$entry"%>
                        </div>

                        <p class="postfeedback">
<a class="permalink" href="/space/<%$entry.path%>" rel="bookmark" title="Permanent Link to <%$subject%>">Permalink</a>
         <% if data["numcomments"] %>
                 <a class="commentslink" href="#" id="trigger_comments-<%$obj%>"><%$numcomments %> comments</a>
            <% else %>
                 No comments
            <% endif %>
 /  <a id="PostComment" href="/exec/comments/<%$obj%>"><%LOCALE id="11" 
string="Post a Comment"%></a>
</p>
</div>
<div dojoType="fins.widget.Comments" refreshUrl="/exec/getcomments/<%$obj%>" id="<%$obj%>_comments" connectorId="trigger_comments-<%$obj%>"></div>
