<% if data["request"]["misc"]["object_is_weblog"] %><% else %>
</div>
    <aside>
    	<p class="dateinfo">JAN<span>31</span></p>
        <div class="post-meta">
       	    <h4>Post Info</h4>
            <ul>
          	    <li class="user"><a href="#"><%$object.author.name%></a></li>
                <li class="time"><a href="#"><%format_date var="$object.created" format="time12"%></a></li>
                <li class="comment"><a href="#"><% sizeof var="$object.comments"%> Comment<%if sizeof(data->object["comments"])!=1 %>s<%endif%></a></li>
                <li class="permalink"><%action_link controller="/space" args="$object.path"%>Permalink</a></li>
            </ul>
        </div>

<!--
       <div class="post-meta">
            <h4>tags</h4>
			<ul class="tags">
	         	<li><a href="index.html" rel="tag">Clean</a></li>
	            <li><a href="index.html" rel="tag">Blog</a></li>
	            <li><a href="index.html" rel="tag">Minimal</a></li>
	         </ul>
       </div>
-->

    </aside>

<!-- /post -->
</article>
<%endif%>
