<!-- this is header.phtml -->
   <link rel="STYLESHEET" type="text/css" href="<%syspref var="site.url"%>/theme/default/default.css"/>
   <link rel="STYLESHEET" type="text/css" href="<% theme show="path"%>style.css"/>

   <!-- IE doesn't like XHTML markup for an empty script container :/ -->

<script type='text/javascript'>
  djConfig = {
    disableFlashStorage : true,
    parseOnLoad: true, 

	<%if data->config->config_name == "dev" %>
    isDebug : true,
    useXDomain: false,
	<% else %>
    isDebug : false,
    useXDomain: true,
	<% endif %>
  };

</script>
<div style="display:none" id="object"><%$obj%></div>

