</xdiv>
 <div class="footer" id="footer"> 
<a href="<%syspref var="site.url"%>">home</a>&nbsp;&nbsp;:&nbsp;&nbsp; 
<a href="/space/contact%20info">contact info</a>
</br>
<center>
copyright &copy; 1995-2006 Bill Welliver
</p></center>
</div>

<script src="/static/javascripts/dojo.js"></script>

<script type='text/javascript'>
dojo.registerModulePath("fins", "<%syspref var="site.url"%>/static/javascripts/fins");
dojo.require("dojo.widget.DateTextbox");
</script>
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="/static/javascripts/rounded-corners.js" type="text/javascript"></script>
<script src="/static/javascripts/bootstrap.js" type="text/javascript"></script>
<script type='text/javascript'>
// insert content inserted previously in the parse process
  <% list_retrieve var="$jsfooter" %>
  make_corners();
</script>
