</xdiv>
 <div class="footer" id="footer"> 
<a href="<%syspref var="site.url"%>">home</a>&nbsp;&nbsp;:&nbsp;&nbsp; 
<a href="/space/contact%20info">contact info</a>
</br>
<center>
copyright &copy; 1995-2006 Bill Welliver
</p></center>
</div>

<xscript src="/static/javascripts/dojo.js"></xscript>

<script src="http://download.dojotoolkit.org/dojo_0.4.2.js"></script>
<script type='text/javascript'>
dojo.registerModulePath("fins", "fins");
</script>
<script src="/static/javascripts/menulayer.js" type="text/javascript"></script>
<script src="/static/javascripts/rounded-corners.js" type="text/javascript"></script>
<script src="/static/javascripts/bootstrap.js" type="text/javascript"></script>

<script type='text/javascript'>
  make_corners();
</script>
