<li> <a href="/space/start">start</a> </li>
<li> <a href="/space/object-index">index</a> </li>
<% if data["user_object"] %>
<li><%action_link controller="/exec" action="logout"%>logout</a></li>
<li><%action_link controller="/account"%>my account</a></li>
<% if data["object_is_weblog"] %>
<li><a href="<%action_url controller="/exec" action="post" args="$metadata.weblog_source_path"%>" id="PostBlog">post blog</a></li>
<% endif %>
<% if data["is_admin"]==1 %>
<li><%action_link controller="/admin"%>admin</a></li>
   <% endif %>
   <% else %>
<li><a href="<%action_url controller="/exec" action="login"%>" id="Login">login</a></li>
<% endif %>

<% if data["user_object"]  %>
<li><a href="<%action_url controller="/exec" action="actions" args="$obj"%>" id="Actions">actions</a> </li>
<% endif %>

