    <link rel="stylesheet" type="text/css" href="<% theme show="path"%>style.css" />
    <link rel="stylesheet" type="text/css" href="/static/lightbox.css" />
    <!-- 
      ** I need some help from Bill on how to get these.
      <link rel="alternate" type="application/atom+xml" href="<%$atom_feed_uri%>" />
      <link rel="alternate" type="application/rss+xml" href="<%$rss_feed_uri%>" />
      <link rel="service.post" type="application/x.atom+xml" href="/atomapi/post" title="<%syspref var="site.name"%>" />
      <link rel="service.edit" type="application/x.atom+xml" href="/atomapi/post" title="<%syspref var="site.name"%>" />
    -->
  </head>
