  <head>
    <script type="application/x-javascript">
      var djConfig = {
	isDebug : true,
      };
    </script>
    <script src="/static/javascripts/dojo.js" type="application/x-javascript" />
    <script type="application/x-javascript">
      dojo.hostend.setModulePrefix("fins.widgets", "../fins/widgets");
    </script>
    <script src="/static/javascripts/menulayer.js" type="application/x-javascript" />
    <script src="/static/javascripts/rounded-corners.js" type="application/x-javascript" />
    <script src="/static/javascripts/bootstrap.js" type="application/x-javascript" />
    <script src="<% theme show="path"%>functions.js" type="application/x-javascript" />
