<body>
  <div id="page">
    <div id="header">
      <img src="<% syspref var="site.logo" %>" alt="<% syspref var="site.name"%>" class="logo" />
      <div id="site_name"><% syspref var="site.name"%></div>
      <div id="site_tagline"><% syspref var="site.tagline"%></div>
    </div>

    <ul id="navigation">
      <li class="navigation" id="start"><a href="/space/start" title="Home page">start</a></li>
      <li class="navigation" id="index"><a href="/space/object-index" title="Index of pages">index</a></li>
      <% if data["user_object"] %>
	<li class="navigation" id="logout"><a href="<%action_url controller="/exec" action="logout"%>"
		  title="Currently logged in as <%$user_object.UserName%>, log out of the site.">logout</a></li>
	<li class="navigation" id="account"><%action_link controller="/account"%>my account</a></li>
	<% if data["object_is_weblog"] %>
	  <li class="navigation" id="blogpost"><a href="<%action_url controller="/exec" action="post" args="$metadata.weblog_source_path"%>" id="PostBlog" 
		  title="Post a blog entry">post blog</a>
	<% endif %>
	<% if data["is_admin"]==1 %>
	  <li class="navigation" id="admin"><a href="<%action_url controller="/admin"%>" title="Administer the site">admin</a></li>
	<% endif %>
      <% else %>
	<li class="navigation" id="login"><a href="<%action_url controller="/exec" action="login"%>" id="Login" 
              	title="Log into the site">login</a>
      <% endif %>
      <% if data["user_object"] %>
	<li class="navigation" id="actions"><a href="/exec/actions/<%$obj%>" title="Edit or change this document">actions</a></li>
      <% endif %>
      <% if !data["in_admin"] %>
	<li class="breadcrumbs"><% breadcrumbs var="$obj" %></li>
      <% endif %>
    </ul>
