        <!-- /main -->
        </div>

        <!-- sidebar -->
		<div id="sidebar">

      	    <div class="about-me">

<%snip snip="themes/default/about-me"%>

            </div>


<%snip snip="themes/default/portlet-1"%>


        <!-- /sidebar -->
		</div>

    <!-- content -->
	</div>

<!-- /content-out -->
</div>
		
<!-- extra -->
<div id="extra-wrap"><div id="extra" class="clearfix">

<%syspref var="site.photo_feed_enable" type="boolean" val="0" store="photo_feed_enable" %>
<%syspref var="site.photo_feed_url" val="NONE" store="photos_url" %>
<%if data->photo_feed_enable  != 0%>
	    <div id="gallery" class="clearfix">
<%image_feed max="10" url="$photos_url" store="photofeed"%>
		    <h3><%$photofeed.title%></h3>

		    <p class="thumbs">
<%foreach var="$photofeed.photos" val="photo"%>
<a href="<%$photo.url%>"><img src="<%$photo.thumbnail%>" width="42" height="43" alt="<%$photo.title%>" /></a>
<%end%>
            </p>

        </div>
<%endif%>

<%syspref var="site.column_1_enable" type="boolean" val="1" store="column_1_enable" %>
<%syspref var="site.column_1_snip" val="themes/default/contact_info" store="column_1_snip" %>
	    <div class="col first">
<%if data->column_1_enable %>
<%snip snip="$column_1_snip"%>
	    </div>
<%endif%>

<%syspref var="site.column_2_enable" type="boolean" val="1" store="column_2_enable" %>
<%syspref var="site.column_2_snip" val="themes/default/site_links" store="column_2_snip" %>
	    <div class="col">
<%if data->column_2_enable %>
<%snip snip="$column_2_snip"%>
	    </div>
<%endif%>

        <div class="col">

            <h3>Recent Comments</h3>

			<%recent_comments max="5" store="recent_comments"%>

	        <div class="recent-comments">
                <ul>
					<%foreach var="$recent_comments" val="comment"%>
			        <li><%action_link controller="/space" args="$comment.object.path"%><%$comment.short_wiki_contents%></a><br /> &#45; <cite><%$comment.author_name%></cite></li>
					<%end%>
			    </ul>
		    </div>

        </div>

        <div class="col">

            <h3>Archives</h3>
<%archive_list weblog="start" max="6" store="archives"%>

	        <div class="footer-list">
			    <ul>
<%foreach var="$archives" val="archive"%><li><a href="<%$archive.url%>"><%$archive.month%></a></li>
<%end%>
			    </ul>
		    </div>

<%syspref var="site.bookmarks_feed_enable" type="boolean" val="0" store="bookmarks_feed_enable" %>
<%syspref var="site.bookmarks_feed_url" val="NONE" store="bookmarks_feed_url" %>
<%if data->bookmarks_feed_enable !=0 %>
<%rss_feed url="$bookmarks_feed_url" store="bookmarks"%>
	    <div id="gallery" class="clearfix">
            <h3>Recent Bookmarks</h3>

	        <div class="footer-list">
			    <ul>
<%foreach var="$bookmarks.items" val="bookmark"%>
				<li><a href="<%$bookmark.data.link%>"><%$bookmark.data.title%></a></li>
<%end%>
			    </ul>
		    </div>

	    </div>
<%endif%>
<!-- /extra -->
</div></div>

<!-- footer -->
<footer>

	<p class="footer-left">
		<%syspref var="site.copyright"%> &nbsp; &nbsp; &nbsp;
		Design by <a href="http://www.styleshout.com/">styleshout</a>
	</p>

	<p class="footer-right">
	   	<%action_link controller="/space"%>Home</a> |
		<%action_link controller="/space" args="object-index"%>Sitemap</a> |
		<%action_link controller="/rss"%>RSS Feed</a> |
        <a href="#top" class="back-to-top">Back to Top</a>
    </p>

<!-- /footer -->
</footer>
