        <!-- /main -->
        </div>

        <!-- sidebar -->
		<div id="sidebar">

      	    <div class="about-me">

<%snip snip="themes/default/about-me"%>

            </div>


<%snip snip="themes/default/portlet-1"%>


        <!-- /sidebar -->
		</div>

    <!-- content -->
	</div>

<!-- /content-out -->
</div>
		
<!-- extra -->
<div id="extra-wrap"><div id="extra" class="clearfix">

	    <div id="gallery" class="clearfix">

		    <h3>Flickr Photos </h3>

		    <p class="thumbs">
			<a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
			<a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
			<a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
			<a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
			<a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
			<a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
			<a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
			<a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
            <a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
			<a href="index.html"><img src="<% theme show="path"%>images/thumb.png" width="42" height="43" alt="thumbnail" /></a>
            </p>

        </div>

	    <div class="col first">

		    <h3>Contact Info</h3>

		    <p>
		    <strong>Phone: </strong>+1234567<br/>
		    <strong>Fax: </strong>+123456789
		    </p>

		    <p><strong>Address: </strong>123 Put Your Address Here</p>
            <p><strong>E-mail: </strong>me@coolblue.com</p>
		    <p>Want more info - go to our <a href="#">contact page</a></p>

            <h3>Updates</h3>

            <ul class="subscribe-stuff">
      	        <li><a title="RSS" href="index.html" rel="nofollow">
				<img alt="RSS" title="RSS" src="<% theme show="path"%>images/social_rss.png" /></a>
			    </li>
      	        <li><a title="Facebook" href="index.html" rel="nofollow">
				<img alt="Facebook" title="Facebook" src="<% theme show="path"%>images/social_facebook.png" /></a>
			    </li>
			    <li><a title="Twitter" href="index.html" rel="nofollow">
				<img alt="Twitter" title="Twitter" src="<% theme show="path"%>images/social_twitter.png" /></a>
			    </li>
			    <li><a title="E-mail this story to a friend!" href="index.html" rel="nofollow">
				<img alt="E-mail this story to a friend!" title="E-mail this story to a friend!" src="<% theme show="path"%>images/social_email.png" /></a>
			    </li>
            </ul>

            <p>Stay up to date. Subscribe via
		    <a href="index">RSS</a>, <a href="index">Facebook</a>,
		    <a href="index">Twitter</a> or <a href="index">Email</a>
		    </p>

	    </div>

	    <div class="col">

   	        <h3>Site Links</h3>

		    <div class="footer-list">
			    <ul>
				    <li><a href="index.html">Home</a></li>
				    <li><a href="index.html">Style Demo</a></li>
				    <li><a href="index.html">Blog</a></li>
				    <li><a href="index.html">Archive</a></li>
				    <li><a href="index.html">About</a></li>
				    <li><a href="index.html">Template Info</a></li>
				    <li><a href="index.html">Site Map</a></li>
			    </ul>
		    </div>

            <h3>Friends</h3>

		    <div class="footer-list">
			    <ul>
				    <li><a href="index.html">consequat molestie</a></li>
				    <li><a href="index.html">sem justo</a></li>
				    <li><a href="index.html">semper</a></li>
				    <li><a href="index.html">magna sed purus</a></li>
				    <li><a href="index.html">tincidunt</a></li>
				    <li><a href="index.html">consequat molestie</a></li>
				    <li><a href="index.html">magna sed purus</a></li>
			    </ul>
		    </div>

	    </div>

        <div class="col">

            <h3>Credits</h3>

            <div class="footer-list">
			    <ul>
				    <li><a href="http://jasonlarose.com/blog/110-free-classy-social-media-icons">
						110 Free Classy Social Media Icons by Jason LaRose
				    </a>
				    </li>
                    <li><a href="http://wefunction.com/2009/05/free-social-icons-app-icons/">
						Free Social Media Icons by WeFunction
				    </a>
				    </li>
                    <li><a href="http://iconsweets2.com/">
						Free Icons by Yummygum
				    </a>
				    </li>
			    </ul>
		    </div>

            <h3>Recent Comments</h3>

			<%recent_comments max="5" store="recent_comments"%>

	        <div class="recent-comments">
                <ul>
					<%foreach var="$recent_comments" val="comment"%>
			        <li><%action_link controller="/space" args="$comment.object.path"%><%$comment.short_wiki_contents%></a><br /> &#45; <cite><%$comment.author_name%></cite></li>
					<%end%>
			    </ul>
		    </div>

        </div>

        <div class="col">

            <h3>Archives</h3>

	        <div class="footer-list">
			    <ul>
				    <li><a href="index.html">January 2010</a></li>
				    <li><a href="index.html">December 2009</a></li>
				    <li><a href="index.html">November 2009</a></li>
				    <li><a href="index.html">October 2009</a></li>
				    <li><a href="index.html">September 2009</a></li>
			    </ul>
		    </div>

            <h3>Recent Bookmarks</h3>

	        <div class="footer-list">
			    <ul>
			    </ul>
		    </div>

	    </div>

<!-- /extra -->
</div></div>

<!-- footer -->
<footer>

	<p class="footer-left">
		<%syspref var="site.copyright"%> &nbsp; &nbsp; &nbsp;
		Design by <a href="http://www.styleshout.com/">styleshout</a>
	</p>

	<p class="footer-right">
	   	<%action_link controller="/space"%>Home</a> |
		<%action_link controller="/space" args="object-index"%>Sitemap</a> |
		<%action_link controller="/rss"%>RSS Feed</a> |
        <a href="#top" class="back-to-top">Back to Top</a>
    </p>

<!-- /footer -->
</footer>