	<%@ include file="top.phtml" %>
        <title><%syspref var="site.name" %> :: <%$title %></title>
        <%$heads %>
        <%@ include file="header.phtml" %>
	<%@ include file="pagebegin.phtml" %>

<!-- we need to provide a header for wiki content. -->
<% breadcrumbs var="$object.path" %>
<%@ include file="space/trackback.phtml" %>
      <% if data["request"]["misc"]["object_is_weblog"] %>
      <% else %>
   <h3><%$title %></h3>
   Created by <%$author_username %>. Last updated by <%$editor_username %>,
<%friendly_date var="$object_version.created" %>. Version #<%$object_version.version%>.
<p>
     <% endif %>
<div class="flash-message"><% flash %></div>
  <%$content%>
<p>
	<% list_store name="jsfooter" val="dojo.require('fins.widget.Comments');" %>
      
<% if data["request"]["misc"]["object_is_weblog"] %>
<% elseif sizeof(data->object["attachments"])%>
<h3>Attachments</h3>
<%@ include file="space/_displayattachments.phtml"%>
<p/>
<%endif %>

      
<% if data["request"]["misc"]["object_is_weblog"] %>
<%else %>
<% if sizeof(data->object["categories"]) %> Posted in <% implode var="$object.category_links" nice="and"%> 
<strong>|</strong> <%endif %>
         <% if data["numcomments"] %>
                 <a href="#" id="trigger_comments-<%$obj%>"><%$numcomments %> comments</a>
            <% else %>
                 No comments
            <% endif %>
 <strong>|</strong> <a id="PostComment" href="/exec/comments/<%$obj%>"><%LOCALE id="11" string="Post a Comment"%></a>|</strong> <a href="/rss/<%$obj%>?type=comments">RSS Feed</a>
  <% if data["metadata"]["trackbacks"] %> <strong>|</strong> <a href="/exec/display_trackbacks/<%$obj%>" 
id="TrackBacks"><%sizeof var="$metadata.trackbacks"%> TrackBacks</a> <% endif %>
  <% if data["metadata"]["pingbacks"] %> <strong>|</strong> <a href="/exec/display_pingbacks/<%$obj%>" 
id="PingBacks"><%sizeof var="$metadata.pingbacks"%> PingBacks</a> <% endif %>
<strong>|</strong> <a id="BackLinks" href="/exec/backlinks/<%$obj%>">BackLinks</a>
         <p/>
			<div dojoType="fins.widget.Comments" refreshUrl="/exec/getcomments/<%$obj%>" id="<%$obj%>_comments" connectorId="trigger_comments-<%$obj%>"></div>
<% endif %>

</div>


<%@include file="footer.phtml" %>
<%@include file="bottom.phtml" %>

